### ISSUE TITLE
CSHL graph genome talk

### ISSUE THREAD

**Issue by evanbiederstedt** [NCBI-Hackathons/Graph_Genomes_CSHL#11]
Just heard talk by Jacob Pritt (student with Steven Salzberg and Ben Langmead at JHU) about their attempt at a graph genome. Other hackathon members were around as well, i.e. @nhansen @nathandunn @DCGenomics)

Discussed some challenges they were trying to tackle with regards to constructing a graph genome (e.g. should we treat all variants as equally relevant? If treated the same, what bias are we introducing?)

Introduced hisat2: https://github.com/infphilo/hisat2, with this background: http://www.nature.com/nature/journal/v526/n7571/full/nature15393.html

Their project could benefit from ours (or at least, there's collaboration to be made here). They're naturally having issues with scaling. We could definite us their benchmarks for our own paper.

What details do you have to add, @DCGenomics? @nhansen? @nathandunn ?

**Comment by DCGenomics** [comment]
Hoping we may be able to do similar tests with the SNP selection method we developed here (its really fast) https://github.com/NCBI-Hackathons/Ultrafast_Mapping_CSHL

**Comment by AlexanderDilthey** [comment]
I've been in touch with Daehwan Kim, the developer of HISAT2. Currently HISAT2 only supports small variants, but if they move to arbitrary graph input or VCFs as input, this would be a very interesting experiment indeed.

**Comment by evanbiederstedt** [comment]
@AlexanderDilthey I wonder what happened with
