### ISSUE TITLE
Name all the things

### ISSUE THREAD

**Issue by evanbiederstedt** [NCBI-Hackathons/Graph_Genomes_CSHL#12]
Obviously not the most pressing concern for this project, but we should come up with a name for this. This includes properly naming our "meta Needleman-Wunsch" algorithm. 

It's something to think about, crew.

**Comment by AlexanderDilthey** [comment]
Perhaps WGG = Whole-genome graph?

Sub-components could then be given names like WGGalign (for the Needleman-Wunsch-like algorithm) etc.

Alex

---

Von: evanbiederstedt notifications@github.com
Gesendet: Sonntag, 30. Oktober 2016 13:39
An: NCBI-Hackathons/Graph_Genomes_CSHL
Betreff: [NCBI-Hackathons/Graph_Genomes_CSHL] Name all the things (#12)

Obviously not the most pressing concern for this project, but we should come up with a name for this. This includes properly naming our "meta Needleman-Wunsch" algorithm.

It's something to think about, crew.

##

**Comment by nathandunn** [comment]
I'm personally a big believer in vowels, but I like the consonants.  WOGG or woGg depending on which trend you want to follow.

**Comment by evanbiederstedt** [comment]
@AlexanderDilthey @nathandunn I'm also a fan of mono-/disyllabic names, though WGG isn't such a bad acronym. It also helps for naming parts of the package, WGGalign, etc. 

WOGG or woGg may not be the best choice, as it's phonetically similar to this English word, which is more recognizable outside of North America: https://en.wikipedia.org/wiki/Wog

Maybe "ScalaGG"? (Scalable Graph Genome?) 
Otherwise, any other variations of WGG?

**Comment by jcoliver** [comment]
Ooo...ScalaGG! Sounds troglodytic (not in a pejorative way, though). 

Could also use "Complete" instead of "Whole" for CoGG/CGG.

**Comment by nathandunn** [comment]
Thanks @evanbiederstedt  . that could have been a disaster.  I also like @jcoliver  recommendations of ScalaGG (first place) or CoGG (second place) and it avoids the problems of user's ever accidentally offending someone.

**Comment by jcoliver** [comment]
@nathandunn Would love to take credit for ScalaGG, but that's @evanbiederstedt 's creation!

**Comment by nhansen** [comment]
ScalaGG might lead people to believe our software is written in the programming language "scala"--I like ScalarGG a little better.  And CoGG might be confused with "cluster of orthologous groups" database Eugene Koonin created: http://nar.oxfordjournals.org/content/28/1/33.full

But I'm loving the idea of having a fun name for the software and project!

--Nancy

**Comment by evanbiederstedt** [comment]
How about "BiGG" or "BigGG"? Like "Big genome graph"? 

Notorious BiGG? 

RE: "Thanks @evanbiederstedt . that could have been a disaster." @nathandunn No problem. Just good to be cautious. Actually, I don't think the word is used unironically anymore (not since the 1970s), but I'm probably wrong.
