### ISSUE TITLE
MetaNWAlgo Pipeline

### ISSUE THREAD

**Issue by aartijajoo88** [NCBI-Hackathons/Graph_Genomes_CSHL#13]
Hello, I missed the conversation on google group about the Dec 9 deadline. 

Evan, what are you working on presently? I had updated MetaNeedalmanWunchAlgo.py few weeks ago, it it complete now. It takes local assembly as input, and gives global assembly. But we need to give it correct input using Alex's file. I think you were writing some code for that. Let me know what part you are working on and/or you would want me to work on, so we can divide the work?

Best,
Aarti

**Comment by evanbiederstedt** [comment]
Hi @aartijajoo88 

I just noticed this! Sorry I missed this issue previously. 

Alex beat us to re-writing this script as a perl script. 
https://github.com/NCBI-Hackathons/Graph_Genomes_CSHL/tree/master/scripts
