### ISSUE TITLE
could not find `dealWithTooManyCIGAROperations.pl`

### ISSUE THREAD

**Issue by iwangtoknow** [NCBI-Hackathons/Graph_Genomes_CSHL#14]
Hi Hack,
I'm following the instruction , I reach the step `FIND_GLOBAL_ALIGNMENTS.pl` but an **Error** occured,
`
Statistics:
	Alignments: 10
	Avg chains per alignment: 154.7
	Alignments with both ends trimmed: 9
	Alignments with left end trimmed: 0
	Alignments with right end trimmed: 1

Done. Produced SAM file forMAFFT.bam.sam.unfiltered

Filtering SAM with command: perl dealWithTooManyCIGAROperations.pl --input forMAFFT.bam.sam.unfiltered --output forMAFFT.bam.sam.unfiltered.filtered
Can't open perl script "dealWithTooManyCIGAROperations.pl": No such file or directory
`
And I couldn't find the perl scripts indeed.
Could you please help me with this?

*Many thanks*
WANG

**Comment by evanbiederstedt** [comment]
Hi @iwangtoknow 

Sorry about that! I had removed this during a recent repo clean-up. The script has now been added. 

Thanks for letting us know about this!

**Comment by evanbiederstedt** [comment]
Hi @iwangtoknow 

I've re-written the script `FIND_GLOBAL_ALIGNMENTS.pl ` such that users must give the path to  `dealWithTooManyCIGAROperations.pl` explicitly, which should hopefully deal with "directory organization issues". 

Let me know if you have any more issues. 

Thanks, Evan

**Comment by iwangtoknow** [comment]
Thanks, Evan,
Sorry for replying so late, recently I keep on my work and have not re-run NovoGraph.

**WANG**
