### ISSUE TITLE
Genomes other than human

### ISSUE THREAD

**Issue by gbdias** [NCBI-Hackathons/Graph_Genomes_CSHL#16]
Hi,

This tool is very interesting. I was wondering if NovoGraph is currently restricted to the human genome? If so, how hard do you think it would be to adapt it to other genomes?

Thanks,
Guilherme

**Comment by AlexanderDilthey** [comment]
Hi Guilherme,

It is not! You only need a reference genome and de novo assemblies to build the graph!

Cheers,

Alex
