### ISSUE TITLE
Issues with alignment processing

### ISSUE THREAD

**Issue by RenzoTale88** [NCBI-Hackathons/Graph_Genomes_CSHL#17]
Hi,
I've aligned cotigs from two non-human assemblies to a reference genome. All assemblies have been generated with pacbio reads. I've performed the alignment of the contigs using bwa (0.7.17) separately for the different contigs, joined everything, sorted and filtered out the unmapped contigs from the new bam file.
When I run the checkBAM_SVs_and_INDELs.pl i get the following output in fromBAM_lengthStatistics.txt:

Produced output file fromBAM_lengthStatistics.txt (only from reads that have primary information)
        read_got_primary: 0
        read_no_primary: 0

Then, when I run the next steps using BAM2ALIGNMENT.pl, I get no AlignmentInput.txt.sortedWithHeader file, and get the following error:

Mismatch query at /exports/cmvm/eddie/eb/groups/prendergast_grp/Andrea/NovoGraph/scripts/BAM2ALIGNMENT.pl line 351.

Do you know whether is a problem related to the length of the reads? Should I use an alternative aligner that works with extremely long contigs (>1Mb)?

Thank you in advance

Andrea

**Comment by nhansen** [comment]
Hi all,

I thought I’d jump in and try to diagnose this issue, and I’m noticing these lines in checkBAM_SVs_and_INDELs.pl:

while(my $alignment = $iterator->next_seq)
{
        my $isPrimary  = (! $alignment->get_tag_values('NOT_PRIMARY'));
        # die if(not $isPrimary);
        next unless($alignment->seq_id eq 'chr20');

Is this intentional? Can we remove the “next” line?

--Nancy

**Comment by AlexanderDilthey** [comment]
@nhansen You're absolutely right, this can be kicked out (and I've just done so)!

@RenzoTale88 Contig length per se should not be an issue -- the case we describe in the paper has many contigs > 1Mb in size. It is very difficult to diagnose what's going on here - either some problem with the function of Bio::DB::HTS that converts SAM entries into alignments, or some problem with our parsing routine of the CIGAR string. One thing you could try is print the values of `$alignment_read_noGaps` and `$supposed_read_sequence` in line 351 (i.e. when the error message is printed). You could also print the ID of the offending aligned sequence (`$readID`) and see whether the corresponding SAM record looks weird in any way. I assume you used bwa for the alignment step, correct?

**Comment by RenzoTale88** [comment]
@AlexanderDilthey, I've tried to edit the line adding the variables to print, but I get the same error as before without additional detail. I've edited the script as follow:

die "Mismatch query $alignment_read_noGaps $supposed_read_sequence $readID" unless($alignment_read_noGaps eq $supposed_read_sequence);

But since I'm not a perl programmer, could you please let me know whether it is the right way to edit it?

I've aligned the reads using BWA 0.7.17, chunking the contigs is separate fasta files, and then combine them in one bam file, sorted, filtered for unmapped reads and then processed as described in the guide.

**Comment by nhansen** [comment]
@RenzoTale88, have you run the new version of checkBAM_SVs_and_INDELs.pl on your filtered BAM file? If these are non-human assemblies, I'm guessing they don't have a "chr20" entry, and the previous version of the script was only processing reads aligned to a reference entry named "chr20". I.e., none of your reads were processed by the previous version of the script.

**Comment by RenzoTale88** [comment]
@nhansen I've made the change to checkBAM_SVs_and_INDELs.pl. This script not work up to a sequence (species2.seq44) where it raise an error for a mismatch line 483. I'm not sure whether the problem is related to the naming of the sequences (species.seqN) or if it is some problem during the alignment phase.

Thank you again for the help

Andrea

**Comment by evanbiederstedt** [comment]
Hi everyone @nhansen @AlexanderDilthey @RenzoTale88 

Apologies I wasn't able to follow this discussion as it took place. 

Just checking the history of the script `checkBAM_SVs_and_INDELs.pl`, it looks like this has been solved:

https://github.com/NCBI-Hackathons/NovoGraph/commits/master/scripts/checkBAM_SVs_and_INDELs.pl

There were major changes by @AlexanderDilthey here:

https://github.com/NCBI-Hackathons/NovoGraph/commit/44cf382f447fa2755defa29caf2b27a3fbe50977

I think this issue can be closed, but feel free to re-open. 

Thanks, Evan
