### ISSUE TITLE
CALLMAFFT.pl with --qsub 1

### ISSUE THREAD

**Issue by TorHou** [NCBI-Hackathons/Graph_Genomes_CSHL#20]
Hello,

i found a small problem when I used CALLMAFFT in the reprocess mode with `--qsub 1`. When the number of regions in `files_to_reprocess` file is smaller than the `$chunkSize` then the calculation of `my $n_chunks = ceil($n_files / $chunkSize);` leads to `$n_chunks` being 1. This in turn means, that the -J parameter for the submission script is set to `1-1` and that is not allowed and this error is the result: `qsub: illegal -J value`

So probably it would be a good idea to check whether the number of files to process is smaller than `$chunkSize` and submit a job array only if necessary.

**Comment by evanbiederstedt** [comment]
Hi @TorHou 

> So probably it would be a good idea to check whether the number of files to process is smaller than $chunkSize and submit a job array only if necessary.

Good point!

I think this is a quick addition to the perl script. If you made a PR, we'll add that feature in. 

Thanks, Evan

**Comment by TorHou** [comment]
Hi Evan,
if my Perl skills were any better I would have done that ;)
but yeah, next time I'll run into this problem I'll fix it.

**Comment by evanbiederstedt** [comment]
Hey @TorHou 

"if my Perl skills were any better I would have done that ;)"

The PI for the Manchot-Group Dilthey would be the gentleman to ask here ;)

Sounds good! Whenever you have a chance, let's create a PR and we'll have a review

**Comment by evanbiederstedt** [comment]
Hi @TorHou 

Was this ever fixed? If so, let's close.
