### ISSUE TITLE
Is it possible to get the contig list for VCF records?

### ISSUE THREAD

**Issue by JYLeeBioinfo** [NCBI-Hackathons/Graph_Genomes_CSHL#21]
Hello!

  I want to find contigs for individual rows of output VCF, so that I can identify the sample from which they are originated.

  If I can get the list of contigs that generated a specific VCF record, I will be able to identify the sample.

  Is there an option to do this task?

Thank you
Jinyoung

**Comment by evanbiederstedt** [comment]
Hi @hd00ljy 

Apologies for the delay. 

I may be misunderstanding---you would like that information written into a VCF column? I think for the VCFs we generated for the paper, that information existed. It depends on the contig names in the input BAMs. 

https://osf.io/3vs42/?view_only=fedd8437d96c4d688f6c40150903d857

Let me know if the information you desire is included in the VCFs above. If so, I think that answers you inquiry (but I could be confused as well). 

Thanks, Evan

**Comment by evanbiederstedt** [comment]
I think this is resolved.
