### ISSUE TITLE
Samples argument for vcf2bam

### ISSUE THREAD

**Issue by jcoliver** [NCBI-Hackathons/Graph_Genomes_CSHL#5]
@ajo2995 Could we get more info on the `--samples` argument in scripts/gg-wrapper-bam2vcf.pl? It sounds like a flat text file with assembly names? Is that right? Is there an example available?

**Comment by jcoliver** [comment]
Is it [list_of_assemblies.txt](https://github.com/NCBI-Hackathons/Graph_Genomes_CSHL/blob/master/examples/list_of_assemblies.txt) ? This file seems to be working!

**Comment by ajo2995** [comment]
yes, but I'm sure you've tried that by now...

**Comment by ajo2995** [comment]
It might be a good idea to increase the window size to 1000000 so the vcf-concat command line doesn't exceed some limit (there will be thousands otherwise)
